c = open('lib/home/home_screen.dart', encoding='utf-8').read()
lines = c.split('\n')
print('Lines:', len(lines))
print('Line 1:', lines[0])
print('Line 30:', lines[29])
print('Line 60:', lines[59])
print('Line 69:', lines[68])
print('Line 150:', lines[149])
print('Last 3:', lines[-3:])
