lines = []
lines.append("import 'package:flutter/material.dart';")
lines.append("import 'package:flutter/services.dart';")
lines.append("import 'package:cached_network_image/cached_network_image.dart';")
lines.append("import 'package:provider/provider.dart';")
lines.append("import 'package:shared_preferences/shared_preferences.dart';")
lines.append("import '../core/api_service.dart';")
lines.append("import '../core/constants.dart';")
lines.append("import '../core/user_auth_provider.dart';")
lines.append("import '../core/location_provider.dart';")
lines.append("import '../models/category_model.dart';")
lines.append("import '../models/ad_model.dart';")
lines.append("import 'ad_detail_screen.dart';")
lines.append("import 'all_categories_screen.dart';")
lines.append("import 'subcategory_screen.dart';")
lines.append("import 'all_recently_viewed_screen.dart';")
lines.append("import 'all_ads_screen.dart';")
lines.append("import '../post_ad/select_category_screen.dart';")
lines.append("import '../auth/user_login_screen.dart';")
lines.append("import '../profile/profile_screen.dart';")
lines.append("import '../my_ads/my_ads_screen.dart';")
lines.append("")
lines.append("const _kRed = Color(0xFFE8192C);")
lines.append("const _kGreen = Color(0xFF6CA651);")
lines.append("")
lines.append("class HomeScreen extends StatefulWidget {")
lines.append("  const HomeScreen({super.key});")
lines.append("  @override")
lines.append("  State<HomeScreen> createState() => _HomeScreenState();")
lines.append("}")
lines.append("")
lines.append("class _HomeScreenState extends State<HomeScreen> {")
lines.append("  final _api = ApiService();")
lines.append("  List<CategoryModel> _categories = [];")
lines.append("  List<AdModel> _ads = [];")
lines.append("  List<AdModel> _recentlyViewed = [];")
lines.append("  List<Map<String, dynamic>> _banners = [];")
lines.append("  bool _loadingCats = true;")
lines.append("  bool _loadingAds = true;")
lines.append("  bool _loadingMore = false;")
lines.append("  int _page = 1;")
lines.append("  int _totalPages = 1;")
lines.append("  int _navIndex = 0;")
lines.append("  int _bannerIndex = 0;")
lines.append("  String _searchQuery = '';")
lines.append("  final _scrollCtrl = ScrollController();")
lines.append("  final _searchCtrl = TextEditingController();")
lines.append("  static const _rvKey = 'recently_viewed_ids';")

with open('lib/home/home_screen.dart', 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines) + '\n')

check = open('lib/home/home_screen.dart', encoding='utf-8').read()
print('Step1 chars:', len(check))
print('Has class HomeScreen:', 'class HomeScreen' in check)
print('Has _HomeScreenState:', '_HomeScreenState' in check)
print('Has _rvKey:', '_rvKey' in check)
